repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --no-ensure-ascii
          - --indent=4
        # exclude ipynb files from this hook since they are not human-readable and are not meant to be edited by hand
        exclude: ^.*\.ipynb$
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: uv run ruff check . --fix --output-format=concise
        language: system
        types_or: [python, pyi]
        pass_filenames: false

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format .
        language: system
        types_or: [python, pyi]
        pass_filenames: false

      - id: ty-check
        name: Ty Check
        entry: uv run ty check --output-format=concise
        language: system
        types_or: [python, pyi]
        pass_filenames: false
