[project]
name = "pokelance"
version = "0.2.17"
description = "A flexible and easy to use pokemon library."
authors = [{ name = "FallenDeity", email = "61227305+FallenDeity@users.noreply.github.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "attrs>=26.1.0",
    "aiofiles>=25.1.0",
    "types-aiofiles>=25.1.0.20260518",
    "niquests>=3.21.0",
    "typing-extensions>=4.16.0",
]

[dependency-groups]
dev = [
    "pre-commit>=2.21.0,<3",
    "auto-changelog>=0.6.0,<0.7",
    "ty>=0.0.72",
    "ruff>=0.16.3",
    "pytest>=9.1.1",
    "pytest-coverage>=0.0",
    "pytest-rerunfailures>=16.5",
    "pytest-asyncio>=1.4.0",
]
docs = [
    "cairosvg>=2.9.0",
    "markdown-exec[ansi]>=1.12.3",
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.26.3",
    "mkdocs-material>=9.7.7",
    "mkdocstrings>=1.0.6",
    "pillow>=12.3.0",
    "pipwin>=0.5.2",
    "pygments>=2.20.0",
    "pytkdocs[numpy-style]>=0.16.5",
]

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--cov-report=term-missing --reruns 3 --reruns-delay 2"

[tool.coverage.run]
source = ["pokelance"]
branch = true

[tool.coverage.report]
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    "if t\\.TYPE_CHECKING",
    "if TYPE_CHECKING",
    "raise NotImplementedError",
]
