# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from typing_extensions import override

from pokelance.cache._async.manager import Berry as BerryCache
from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.client.async_client import PokeLanceAsyncClient

__all__: tuple[str, ...] = ("Berry", "setup")


class Berry(AsyncBaseExtension[BerryCache]):
    """Extension for berry related endpoints."""

    @override
    async def setup(self) -> None:
        routes = {
            "berry": Endpoint.get_berry_endpoints(),
            "berry_firmness": Endpoint.get_berry_firmness_endpoints(),
            "berry_flavor": Endpoint.get_berry_flavor_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Berry", category, data["results"])

    def get_berry(self, name: str | int) -> models.Berry | None:
        """Gets a berry from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Berry | None
            The cached model or None.

        Examples
        --------
        ```python
        berry = client.berry.get_berry("cheri")
        if berry:
            print(berry)
        ```"""
        route = Endpoint.get_berry(name)
        self._validate_resource(self._cache_group.berry, name, route)
        return self._cache_group.berry.get(route, None)

    async def fetch_berry(self, name: str | int) -> models.Berry:
        """Fetches a berry from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Berry
            The fetched model.

        Examples
        --------
        ```python
        berry = await client.berry.fetch_berry("cheri")
        print(berry)
        ```"""
        route = Endpoint.get_berry(name)
        self._validate_resource(self._cache_group.berry, name, route)
        data = await self._client.request(route)
        return self._cache_group.berry.setdefault(route, self._cache_group.berry.from_payload(data))

    def get_berry_firmness(self, name: str | int) -> models.BerryFirmness | None:
        """Gets a berry firmness from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.BerryFirmness | None
            The cached model or None.

        Examples
        --------
        ```python
        firmness = client.berry.get_berry_firmness("very-soft")
        if firmness:
            print(firmness)
        ```"""
        route = Endpoint.get_berry_firmness(name)
        self._validate_resource(self._cache_group.berry_firmness, name, route)
        return self._cache_group.berry_firmness.get(route, None)

    async def fetch_berry_firmness(self, name: str | int) -> models.BerryFirmness:
        """Fetches a berry firmness from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.BerryFirmness
            The fetched model.

        Examples
        --------
        ```python
        firmness = await client.berry.fetch_berry_firmness("very-soft")
        print(firmness)
        ```"""
        route = Endpoint.get_berry_firmness(name)
        self._validate_resource(self._cache_group.berry_firmness, name, route)
        data = await self._client.request(route)
        return self._cache_group.berry_firmness.setdefault(route, self._cache_group.berry_firmness.from_payload(data))

    def get_berry_flavor(self, name: str | int) -> models.BerryFlavor | None:
        """Gets a berry flavor from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.BerryFlavor | None
            The cached model or None.

        Examples
        --------
        ```python
        flavor = client.berry.get_berry_flavor("spicy")
        if flavor:
            print(flavor)
        ```"""
        route = Endpoint.get_berry_flavor(name)
        self._validate_resource(self._cache_group.berry_flavor, name, route)
        return self._cache_group.berry_flavor.get(route, None)

    async def fetch_berry_flavor(self, name: str | int) -> models.BerryFlavor:
        """Fetches a berry flavor from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.BerryFlavor
            The fetched model.

        Examples
        --------
        ```python
        flavor = await client.berry.fetch_berry_flavor("spicy")
        print(flavor)
        ```"""
        route = Endpoint.get_berry_flavor(name)
        self._validate_resource(self._cache_group.berry_flavor, name, route)
        data = await self._client.request(route)
        return self._cache_group.berry_flavor.setdefault(route, self._cache_group.berry_flavor.from_payload(data))


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the berry extension."""
    lance.add_extension("berry", Berry(lance.http))
