# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Contest as ContestCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[ContestCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Contest", "setup")


class Contest(_Base):
    """Extension for contest related endpoints."""

    async def setup(self) -> None:
        routes = {
            "contest_type": Endpoint.get_contest_type_endpoints(),
            "contest_effect": Endpoint.get_contest_effect_endpoints(),
            "super_contest_effect": Endpoint.get_super_contest_effect_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Contest", category, data["results"])

    def get_contest_type(self, name: str | int) -> models.ContestType | None:
        """Gets a contest type from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ContestType | None
            The cached model or None."""
        route = Endpoint.get_contest_type(name)
        self._validate_resource(self._cache_group.contest_type, name, route)
        return self._cache_group.contest_type.get(route, None)

    async def fetch_contest_type(self, name: str | int) -> models.ContestType:
        """Fetches a contest type from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ContestType
            The fetched model."""
        route = Endpoint.get_contest_type(name)
        self._validate_resource(self._cache_group.contest_type, name, route)
        data = await self._client.request(route)
        return self._cache_group.contest_type.setdefault(route, self._cache_group.contest_type.from_payload(data))

    def get_contest_effect(self, id: int) -> models.ContestEffect | None:
        """Gets a contest effect from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.ContestEffect | None
            The cached model or None."""
        route = Endpoint.get_contest_effect(id)
        self._validate_resource(self._cache_group.contest_effect, id, route)
        return self._cache_group.contest_effect.get(route, None)

    async def fetch_contest_effect(self, id: int) -> models.ContestEffect:
        """Fetches a contest effect from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.ContestEffect
            The fetched model."""
        route = Endpoint.get_contest_effect(id)
        self._validate_resource(self._cache_group.contest_effect, id, route)
        data = await self._client.request(route)
        return self._cache_group.contest_effect.setdefault(route, self._cache_group.contest_effect.from_payload(data))

    def get_super_contest_effect(self, id: int) -> models.SuperContestEffect | None:
        """Gets a super contest effect from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.SuperContestEffect | None
            The cached model or None."""
        route = Endpoint.get_super_contest_effect(id)
        self._validate_resource(self._cache_group.super_contest_effect, id, route)
        return self._cache_group.super_contest_effect.get(route, None)

    async def fetch_super_contest_effect(self, id: int) -> models.SuperContestEffect:
        """Fetches a super contest effect from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.SuperContestEffect
            The fetched model."""
        route = Endpoint.get_super_contest_effect(id)
        self._validate_resource(self._cache_group.super_contest_effect, id, route)
        data = await self._client.request(route)
        return self._cache_group.super_contest_effect.setdefault(
            route, self._cache_group.super_contest_effect.from_payload(data)
        )


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the contest extension."""
    lance.add_extension("contest", Contest(lance.http))
