# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Encounter as EncounterCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[EncounterCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Encounter", "setup")


class Encounter(_Base):
    """Extension for encounter related endpoints."""

    async def setup(self) -> None:
        routes = {
            "encounter_method": Endpoint.get_encounter_method_endpoints(),
            "encounter_condition": Endpoint.get_encounter_condition_endpoints(),
            "encounter_condition_value": Endpoint.get_encounter_condition_value_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Encounter", category, data["results"])

    def get_encounter_method(self, name: str | int) -> models.EncounterMethod | None:
        """Gets a encounter method from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterMethod | None
            The cached model or None."""
        route = Endpoint.get_encounter_method(name)
        self._validate_resource(self._cache_group.encounter_method, name, route)
        return self._cache_group.encounter_method.get(route, None)

    async def fetch_encounter_method(self, name: str | int) -> models.EncounterMethod:
        """Fetches a encounter method from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterMethod
            The fetched model."""
        route = Endpoint.get_encounter_method(name)
        self._validate_resource(self._cache_group.encounter_method, name, route)
        data = await self._client.request(route)
        return self._cache_group.encounter_method.setdefault(
            route, self._cache_group.encounter_method.from_payload(data)
        )

    def get_encounter_condition(self, name: str | int) -> models.EncounterCondition | None:
        """Gets a encounter condition from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterCondition | None
            The cached model or None."""
        route = Endpoint.get_encounter_condition(name)
        self._validate_resource(self._cache_group.encounter_condition, name, route)
        return self._cache_group.encounter_condition.get(route, None)

    async def fetch_encounter_condition(self, name: str | int) -> models.EncounterCondition:
        """Fetches a encounter condition from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterCondition
            The fetched model."""
        route = Endpoint.get_encounter_condition(name)
        self._validate_resource(self._cache_group.encounter_condition, name, route)
        data = await self._client.request(route)
        return self._cache_group.encounter_condition.setdefault(
            route, self._cache_group.encounter_condition.from_payload(data)
        )

    def get_encounter_condition_value(self, name: str | int) -> models.EncounterConditionValue | None:
        """Gets a encounter condition value from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterConditionValue | None
            The cached model or None."""
        route = Endpoint.get_encounter_condition_value(name)
        self._validate_resource(self._cache_group.encounter_condition_value, name, route)
        return self._cache_group.encounter_condition_value.get(route, None)

    async def fetch_encounter_condition_value(self, name: str | int) -> models.EncounterConditionValue:
        """Fetches a encounter condition value from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EncounterConditionValue
            The fetched model."""
        route = Endpoint.get_encounter_condition_value(name)
        self._validate_resource(self._cache_group.encounter_condition_value, name, route)
        data = await self._client.request(route)
        return self._cache_group.encounter_condition_value.setdefault(
            route, self._cache_group.encounter_condition_value.from_payload(data)
        )


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the encounter extension."""
    lance.add_extension("encounter", Encounter(lance.http))
