# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from typing_extensions import override

from pokelance.cache._async.manager import Evolution as EvolutionCache
from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.client.async_client import PokeLanceAsyncClient

__all__: tuple[str, ...] = ("Evolution", "setup")


class Evolution(AsyncBaseExtension[EvolutionCache]):
    """Extension for evolution related endpoints."""

    @override
    async def setup(self) -> None:
        routes = {
            "evolution_chain": Endpoint.get_evolution_chain_endpoints(),
            "evolution_trigger": Endpoint.get_evolution_trigger_endpoints(),
            "evolution_variable": Endpoint.get_evolution_variable_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Evolution", category, data["results"])

    def get_evolution_chain(self, id: int) -> models.EvolutionChain | None:
        """Gets a evolution chain from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.EvolutionChain | None
            The cached model or None.

        Examples
        --------
        ```python
        chain = client.evolution.get_evolution_chain(1)
        if chain:
            print(chain)
        ```"""
        route = Endpoint.get_evolution_chain(id)
        self._validate_resource(self._cache_group.evolution_chain, id, route)
        return self._cache_group.evolution_chain.get(route, None)

    async def fetch_evolution_chain(self, id: int) -> models.EvolutionChain:
        """Fetches a evolution chain from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.EvolutionChain
            The fetched model.

        Examples
        --------
        ```python
        chain = await client.evolution.fetch_evolution_chain(1)
        print(chain)
        ```"""
        route = Endpoint.get_evolution_chain(id)
        self._validate_resource(self._cache_group.evolution_chain, id, route)
        data = await self._client.request(route)
        return self._cache_group.evolution_chain.setdefault(route, self._cache_group.evolution_chain.from_payload(data))

    def get_evolution_trigger(self, name: str | int) -> models.EvolutionTrigger | None:
        """Gets a evolution trigger from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionTrigger | None
            The cached model or None.

        Examples
        --------
        ```python
        trigger = client.evolution.get_evolution_trigger("level-up")
        if trigger:
            print(trigger)
        ```"""
        route = Endpoint.get_evolution_trigger(name)
        self._validate_resource(self._cache_group.evolution_trigger, name, route)
        return self._cache_group.evolution_trigger.get(route, None)

    async def fetch_evolution_trigger(self, name: str | int) -> models.EvolutionTrigger:
        """Fetches a evolution trigger from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionTrigger
            The fetched model.

        Examples
        --------
        ```python
        trigger = await client.evolution.fetch_evolution_trigger("level-up")
        print(trigger)
        ```"""
        route = Endpoint.get_evolution_trigger(name)
        self._validate_resource(self._cache_group.evolution_trigger, name, route)
        data = await self._client.request(route)
        return self._cache_group.evolution_trigger.setdefault(
            route, self._cache_group.evolution_trigger.from_payload(data)
        )

    def get_evolution_variable(self, name: str | int) -> models.EvolutionVariable | None:
        """Gets a evolution variable from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionVariable | None
            The cached model or None.

        Examples
        --------
        ```python
        variable = client.evolution.get_evolution_variable("encryption-constant")
        if variable:
            print(variable)
        ```"""
        route = Endpoint.get_evolution_variable(name)
        self._validate_resource(self._cache_group.evolution_variable, name, route)
        return self._cache_group.evolution_variable.get(route, None)

    async def fetch_evolution_variable(self, name: str | int) -> models.EvolutionVariable:
        """Fetches a evolution variable from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionVariable
            The fetched model.

        Examples
        --------
        ```python
        variable = await client.evolution.fetch_evolution_variable("encryption-constant")
        print(variable)
        ```"""
        route = Endpoint.get_evolution_variable(name)
        self._validate_resource(self._cache_group.evolution_variable, name, route)
        data = await self._client.request(route)
        return self._cache_group.evolution_variable.setdefault(
            route, self._cache_group.evolution_variable.from_payload(data)
        )


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the evolution extension."""
    lance.add_extension("evolution", Evolution(lance.http))
