# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from typing_extensions import override

from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Item as ItemCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[ItemCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Item", "setup")


class Item(_Base):
    """Extension for item related endpoints."""

    @override
    async def setup(self) -> None:
        routes = {
            "item": Endpoint.get_item_endpoints(),
            "item_attribute": Endpoint.get_item_attribute_endpoints(),
            "item_category": Endpoint.get_item_category_endpoints(),
            "item_fling_effect": Endpoint.get_item_fling_effect_endpoints(),
            "item_pocket": Endpoint.get_item_pocket_endpoints(),
            "currency": Endpoint.get_currency_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Item", category, data["results"])

    def get_item(self, name: str | int) -> models.Item | None:
        """Gets a item from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Item | None
            The cached model or None."""
        route = Endpoint.get_item(name)
        self._validate_resource(self._cache_group.item, name, route)
        return self._cache_group.item.get(route, None)

    async def fetch_item(self, name: str | int) -> models.Item:
        """Fetches a item from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Item
            The fetched model."""
        route = Endpoint.get_item(name)
        self._validate_resource(self._cache_group.item, name, route)
        data = await self._client.request(route)
        return self._cache_group.item.setdefault(route, self._cache_group.item.from_payload(data))

    def get_item_attribute(self, name: str | int) -> models.ItemAttribute | None:
        """Gets a item attribute from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemAttribute | None
            The cached model or None."""
        route = Endpoint.get_item_attribute(name)
        self._validate_resource(self._cache_group.item_attribute, name, route)
        return self._cache_group.item_attribute.get(route, None)

    async def fetch_item_attribute(self, name: str | int) -> models.ItemAttribute:
        """Fetches a item attribute from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemAttribute
            The fetched model."""
        route = Endpoint.get_item_attribute(name)
        self._validate_resource(self._cache_group.item_attribute, name, route)
        data = await self._client.request(route)
        return self._cache_group.item_attribute.setdefault(route, self._cache_group.item_attribute.from_payload(data))

    def get_item_category(self, name: str | int) -> models.ItemCategory | None:
        """Gets a item category from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemCategory | None
            The cached model or None."""
        route = Endpoint.get_item_category(name)
        self._validate_resource(self._cache_group.item_category, name, route)
        return self._cache_group.item_category.get(route, None)

    async def fetch_item_category(self, name: str | int) -> models.ItemCategory:
        """Fetches a item category from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemCategory
            The fetched model."""
        route = Endpoint.get_item_category(name)
        self._validate_resource(self._cache_group.item_category, name, route)
        data = await self._client.request(route)
        return self._cache_group.item_category.setdefault(route, self._cache_group.item_category.from_payload(data))

    def get_item_fling_effect(self, name: str | int) -> models.ItemFlingEffect | None:
        """Gets a item fling effect from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemFlingEffect | None
            The cached model or None."""
        route = Endpoint.get_item_fling_effect(name)
        self._validate_resource(self._cache_group.item_fling_effect, name, route)
        return self._cache_group.item_fling_effect.get(route, None)

    async def fetch_item_fling_effect(self, name: str | int) -> models.ItemFlingEffect:
        """Fetches a item fling effect from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemFlingEffect
            The fetched model."""
        route = Endpoint.get_item_fling_effect(name)
        self._validate_resource(self._cache_group.item_fling_effect, name, route)
        data = await self._client.request(route)
        return self._cache_group.item_fling_effect.setdefault(
            route, self._cache_group.item_fling_effect.from_payload(data)
        )

    def get_item_pocket(self, name: str | int) -> models.ItemPocket | None:
        """Gets a item pocket from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemPocket | None
            The cached model or None."""
        route = Endpoint.get_item_pocket(name)
        self._validate_resource(self._cache_group.item_pocket, name, route)
        return self._cache_group.item_pocket.get(route, None)

    async def fetch_item_pocket(self, name: str | int) -> models.ItemPocket:
        """Fetches a item pocket from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.ItemPocket
            The fetched model."""
        route = Endpoint.get_item_pocket(name)
        self._validate_resource(self._cache_group.item_pocket, name, route)
        data = await self._client.request(route)
        return self._cache_group.item_pocket.setdefault(route, self._cache_group.item_pocket.from_payload(data))

    def get_currency(self, name: str | int) -> models.Currency | None:
        """Gets a currency from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Currency | None
            The cached model or None."""
        route = Endpoint.get_currency(name)
        self._validate_resource(self._cache_group.currency, name, route)
        return self._cache_group.currency.get(route, None)

    async def fetch_currency(self, name: str | int) -> models.Currency:
        """Fetches a currency from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Currency
            The fetched model."""
        route = Endpoint.get_currency(name)
        self._validate_resource(self._cache_group.currency, name, route)
        data = await self._client.request(route)
        return self._cache_group.currency.setdefault(route, self._cache_group.currency.from_payload(data))


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the item extension."""
    lance.add_extension("item", Item(lance.http))
