# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Machine as MachineCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[MachineCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Machine", "setup")


class Machine(_Base):
    """Extension for machine related endpoints."""

    async def setup(self) -> None:
        routes = {"machine": Endpoint.get_machine_endpoints()}
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Machine", category, data["results"])

    def get_machine(self, id: int) -> models.Machine | None:
        """Gets a machine from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Machine | None
            The cached model or None."""
        route = Endpoint.get_machine(id)
        self._validate_resource(self._cache_group.machine, id, route)
        return self._cache_group.machine.get(route, None)

    async def fetch_machine(self, id: int) -> models.Machine:
        """Fetches a machine from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Machine
            The fetched model."""
        route = Endpoint.get_machine(id)
        self._validate_resource(self._cache_group.machine, id, route)
        data = await self._client.request(route)
        return self._cache_group.machine.setdefault(route, self._cache_group.machine.from_payload(data))


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the machine extension."""
    lance.add_extension("machine", Machine(lance.http))
