# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from pokelance.endpoints import Endpoint
from pokelance.ext._async._base import AsyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Pokemon as PokemonCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[PokemonCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Pokemon", "setup")


class Pokemon(_Base):
    """Extension for pokemon related endpoints."""

    async def setup(self) -> None:
        routes = {
            "ability": Endpoint.get_ability_endpoints(),
            "characteristic": Endpoint.get_characteristic_endpoints(),
            "egg_group": Endpoint.get_egg_group_endpoints(),
            "gender": Endpoint.get_gender_endpoints(),
            "growth_rate": Endpoint.get_growth_rate_endpoints(),
            "nature": Endpoint.get_nature_endpoints(),
            "pokeathlon_stat": Endpoint.get_pokeathlon_stat_endpoints(),
            "pokemon": Endpoint.get_pokemon_endpoints(),
            "pokemon_color": Endpoint.get_pokemon_color_endpoints(),
            "pokemon_form": Endpoint.get_pokemon_form_endpoints(),
            "pokemon_habitat": Endpoint.get_pokemon_habitat_endpoints(),
            "pokemon_shape": Endpoint.get_pokemon_shape_endpoints(),
            "pokemon_species": Endpoint.get_pokemon_species_endpoints(),
            "stat": Endpoint.get_stat_endpoints(),
            "type": Endpoint.get_type_endpoints(),
            "location_area_encounter": Endpoint.get_location_area_encounter_endpoints(),
        }
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Pokemon", category, data["results"])

    def get_ability(self, name: str | int) -> models.Ability | None:
        """Gets a ability from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Ability | None
            The cached model or None."""
        route = Endpoint.get_ability(name)
        self._validate_resource(self._cache_group.ability, name, route)
        return self._cache_group.ability.get(route, None)

    async def fetch_ability(self, name: str | int) -> models.Ability:
        """Fetches a ability from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Ability
            The fetched model."""
        route = Endpoint.get_ability(name)
        self._validate_resource(self._cache_group.ability, name, route)
        data = await self._client.request(route)
        return self._cache_group.ability.setdefault(route, self._cache_group.ability.from_payload(data))

    def get_characteristic(self, id: int) -> models.Characteristic | None:
        """Gets a characteristic from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Characteristic | None
            The cached model or None."""
        route = Endpoint.get_characteristic(id)
        self._validate_resource(self._cache_group.characteristic, id, route)
        return self._cache_group.characteristic.get(route, None)

    async def fetch_characteristic(self, id: int) -> models.Characteristic:
        """Fetches a characteristic from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Characteristic
            The fetched model."""
        route = Endpoint.get_characteristic(id)
        self._validate_resource(self._cache_group.characteristic, id, route)
        data = await self._client.request(route)
        return self._cache_group.characteristic.setdefault(route, self._cache_group.characteristic.from_payload(data))

    def get_egg_group(self, name: str | int) -> models.EggGroup | None:
        """Gets a egg group from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EggGroup | None
            The cached model or None."""
        route = Endpoint.get_egg_group(name)
        self._validate_resource(self._cache_group.egg_group, name, route)
        return self._cache_group.egg_group.get(route, None)

    async def fetch_egg_group(self, name: str | int) -> models.EggGroup:
        """Fetches a egg group from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EggGroup
            The fetched model."""
        route = Endpoint.get_egg_group(name)
        self._validate_resource(self._cache_group.egg_group, name, route)
        data = await self._client.request(route)
        return self._cache_group.egg_group.setdefault(route, self._cache_group.egg_group.from_payload(data))

    def get_gender(self, name: str | int) -> models.Gender | None:
        """Gets a gender from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Gender | None
            The cached model or None."""
        route = Endpoint.get_gender(name)
        self._validate_resource(self._cache_group.gender, name, route)
        return self._cache_group.gender.get(route, None)

    async def fetch_gender(self, name: str | int) -> models.Gender:
        """Fetches a gender from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Gender
            The fetched model."""
        route = Endpoint.get_gender(name)
        self._validate_resource(self._cache_group.gender, name, route)
        data = await self._client.request(route)
        return self._cache_group.gender.setdefault(route, self._cache_group.gender.from_payload(data))

    def get_growth_rate(self, name: str | int) -> models.GrowthRate | None:
        """Gets a growth rate from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.GrowthRate | None
            The cached model or None."""
        route = Endpoint.get_growth_rate(name)
        self._validate_resource(self._cache_group.growth_rate, name, route)
        return self._cache_group.growth_rate.get(route, None)

    async def fetch_growth_rate(self, name: str | int) -> models.GrowthRate:
        """Fetches a growth rate from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.GrowthRate
            The fetched model."""
        route = Endpoint.get_growth_rate(name)
        self._validate_resource(self._cache_group.growth_rate, name, route)
        data = await self._client.request(route)
        return self._cache_group.growth_rate.setdefault(route, self._cache_group.growth_rate.from_payload(data))

    def get_nature(self, name: str | int) -> models.Nature | None:
        """Gets a nature from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Nature | None
            The cached model or None."""
        route = Endpoint.get_nature(name)
        self._validate_resource(self._cache_group.nature, name, route)
        return self._cache_group.nature.get(route, None)

    async def fetch_nature(self, name: str | int) -> models.Nature:
        """Fetches a nature from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Nature
            The fetched model."""
        route = Endpoint.get_nature(name)
        self._validate_resource(self._cache_group.nature, name, route)
        data = await self._client.request(route)
        return self._cache_group.nature.setdefault(route, self._cache_group.nature.from_payload(data))

    def get_pokeathlon_stat(self, name: str | int) -> models.PokeathlonStat | None:
        """Gets a pokeathlon stat from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokeathlonStat | None
            The cached model or None."""
        route = Endpoint.get_pokeathlon_stat(name)
        self._validate_resource(self._cache_group.pokeathlon_stat, name, route)
        return self._cache_group.pokeathlon_stat.get(route, None)

    async def fetch_pokeathlon_stat(self, name: str | int) -> models.PokeathlonStat:
        """Fetches a pokeathlon stat from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokeathlonStat
            The fetched model."""
        route = Endpoint.get_pokeathlon_stat(name)
        self._validate_resource(self._cache_group.pokeathlon_stat, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokeathlon_stat.setdefault(route, self._cache_group.pokeathlon_stat.from_payload(data))

    def get_pokemon(self, name: str | int) -> models.Pokemon | None:
        """Gets a pokemon from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Pokemon | None
            The cached model or None."""
        route = Endpoint.get_pokemon(name)
        self._validate_resource(self._cache_group.pokemon, name, route)
        return self._cache_group.pokemon.get(route, None)

    async def fetch_pokemon(self, name: str | int) -> models.Pokemon:
        """Fetches a pokemon from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Pokemon
            The fetched model."""
        route = Endpoint.get_pokemon(name)
        self._validate_resource(self._cache_group.pokemon, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon.setdefault(route, self._cache_group.pokemon.from_payload(data))

    def get_pokemon_color(self, name: str | int) -> models.PokemonColor | None:
        """Gets a pokemon color from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonColor | None
            The cached model or None."""
        route = Endpoint.get_pokemon_color(name)
        self._validate_resource(self._cache_group.pokemon_color, name, route)
        return self._cache_group.pokemon_color.get(route, None)

    async def fetch_pokemon_color(self, name: str | int) -> models.PokemonColor:
        """Fetches a pokemon color from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonColor
            The fetched model."""
        route = Endpoint.get_pokemon_color(name)
        self._validate_resource(self._cache_group.pokemon_color, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon_color.setdefault(route, self._cache_group.pokemon_color.from_payload(data))

    def get_pokemon_form(self, name: str | int) -> models.PokemonForm | None:
        """Gets a pokemon form from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonForm | None
            The cached model or None."""
        route = Endpoint.get_pokemon_form(name)
        self._validate_resource(self._cache_group.pokemon_form, name, route)
        return self._cache_group.pokemon_form.get(route, None)

    async def fetch_pokemon_form(self, name: str | int) -> models.PokemonForm:
        """Fetches a pokemon form from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonForm
            The fetched model."""
        route = Endpoint.get_pokemon_form(name)
        self._validate_resource(self._cache_group.pokemon_form, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon_form.setdefault(route, self._cache_group.pokemon_form.from_payload(data))

    def get_pokemon_habitat(self, name: str | int) -> models.PokemonHabitats | None:
        """Gets a pokemon habitat from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonHabitats | None
            The cached model or None."""
        route = Endpoint.get_pokemon_habitat(name)
        self._validate_resource(self._cache_group.pokemon_habitat, name, route)
        return self._cache_group.pokemon_habitat.get(route, None)

    async def fetch_pokemon_habitat(self, name: str | int) -> models.PokemonHabitats:
        """Fetches a pokemon habitat from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonHabitats
            The fetched model."""
        route = Endpoint.get_pokemon_habitat(name)
        self._validate_resource(self._cache_group.pokemon_habitat, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon_habitat.setdefault(route, self._cache_group.pokemon_habitat.from_payload(data))

    def get_pokemon_shape(self, name: str | int) -> models.PokemonShape | None:
        """Gets a pokemon shape from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonShape | None
            The cached model or None."""
        route = Endpoint.get_pokemon_shape(name)
        self._validate_resource(self._cache_group.pokemon_shape, name, route)
        return self._cache_group.pokemon_shape.get(route, None)

    async def fetch_pokemon_shape(self, name: str | int) -> models.PokemonShape:
        """Fetches a pokemon shape from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonShape
            The fetched model."""
        route = Endpoint.get_pokemon_shape(name)
        self._validate_resource(self._cache_group.pokemon_shape, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon_shape.setdefault(route, self._cache_group.pokemon_shape.from_payload(data))

    def get_pokemon_species(self, name: str | int) -> models.PokemonSpecies | None:
        """Gets a pokemon species from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonSpecies | None
            The cached model or None."""
        route = Endpoint.get_pokemon_species(name)
        self._validate_resource(self._cache_group.pokemon_species, name, route)
        return self._cache_group.pokemon_species.get(route, None)

    async def fetch_pokemon_species(self, name: str | int) -> models.PokemonSpecies:
        """Fetches a pokemon species from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.PokemonSpecies
            The fetched model."""
        route = Endpoint.get_pokemon_species(name)
        self._validate_resource(self._cache_group.pokemon_species, name, route)
        data = await self._client.request(route)
        return self._cache_group.pokemon_species.setdefault(route, self._cache_group.pokemon_species.from_payload(data))

    def get_stat(self, name: str | int) -> models.Stat | None:
        """Gets a stat from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Stat | None
            The cached model or None."""
        route = Endpoint.get_stat(name)
        self._validate_resource(self._cache_group.stat, name, route)
        return self._cache_group.stat.get(route, None)

    async def fetch_stat(self, name: str | int) -> models.Stat:
        """Fetches a stat from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Stat
            The fetched model."""
        route = Endpoint.get_stat(name)
        self._validate_resource(self._cache_group.stat, name, route)
        data = await self._client.request(route)
        return self._cache_group.stat.setdefault(route, self._cache_group.stat.from_payload(data))

    def get_type(self, name: str | int) -> models.Type | None:
        """Gets a type from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Type | None
            The cached model or None."""
        route = Endpoint.get_type(name)
        self._validate_resource(self._cache_group.type, name, route)
        return self._cache_group.type.get(route, None)

    async def fetch_type(self, name: str | int) -> models.Type:
        """Fetches a type from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Type
            The fetched model."""
        route = Endpoint.get_type(name)
        self._validate_resource(self._cache_group.type, name, route)
        data = await self._client.request(route)
        return self._cache_group.type.setdefault(route, self._cache_group.type.from_payload(data))

    def get_location_area_encounter(self, name: str | int) -> list[models.LocationAreaEncounter] | None:
        """Gets a location area encounter from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        list[models.LocationAreaEncounter] | None
            The cached model or None."""
        route = Endpoint.get_location_area_encounter(name)
        self._validate_resource(self._cache_group.location_area_encounter, name, route)
        return self._cache_group.location_area_encounter.get(route, None)

    async def fetch_location_area_encounter(self, name: str | int) -> list[models.LocationAreaEncounter]:
        """Fetches a location area encounter from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        list[models.LocationAreaEncounter]
            The fetched model."""
        route = Endpoint.get_location_area_encounter(name)
        self._validate_resource(self._cache_group.location_area_encounter, name, route)
        data = await self._client.request(route)
        return self._cache_group.location_area_encounter.setdefault(
            route, self._cache_group.location_area_encounter.from_payload(data)
        )


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the pokemon extension."""
    lance.add_extension("pokemon", Pokemon(lance.http))
