# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import asyncio
import typing as t

from pokelance.ext._async._base import AsyncBaseExtension
from pokelance.http.endpoints import Endpoint

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache._async.manager import Utility as UtilityCache
    from pokelance.client.async_client import PokeLanceAsyncClient

    _Base = AsyncBaseExtension[UtilityCache]
else:
    _Base = AsyncBaseExtension

__all__: tuple[str, ...] = ("Utility", "setup")


class Utility(_Base):
    """Extension for utility related endpoints."""

    async def setup(self) -> None:
        routes = {"language": Endpoint.get_language_endpoints()}
        results = await asyncio.gather(*(self._client.request(r) for r in routes.values()))
        for category, data in zip(routes.keys(), results, strict=False):
            self._cache_manager.load_documents("Utility", category, data["results"])

    def get_language(self, id: int) -> models.Language | None:
        """Gets a language from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Language | None
            The cached model or None."""
        route = Endpoint.get_language(id)
        self._validate_resource(self._cache_group.language, id, route)
        return self._cache_group.language.get(route, None)

    async def fetch_language(self, id: int) -> models.Language:
        """Fetches a language from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Language
            The fetched model."""
        route = Endpoint.get_language(id)
        self._validate_resource(self._cache_group.language, id, route)
        data = await self._client.request(route)
        return self._cache_group.language.setdefault(route, self._cache_group.language.from_payload(data))

    def get_api_metadata(self) -> models.APIMetadata | None:
        """Gets a api metadata from the cache.

        Returns
        -------
        models.APIMetadata | None
            The cached model or None."""
        route = Endpoint.get_api_metadata()
        return self._cache_group.api_metadata.get(route, None)

    async def fetch_api_metadata(self) -> models.APIMetadata:
        """Fetches a api metadata from the API.

        Returns
        -------
        models.APIMetadata
            The fetched model."""
        route = Endpoint.get_api_metadata()
        data = await self._client.request(route)
        return self._cache_group.api_metadata.setdefault(route, self._cache_group.api_metadata.from_payload(data))


def setup(lance: PokeLanceAsyncClient) -> None:
    """Sets up the utility extension."""
    lance.add_extension("utility", Utility(lance.http))
