# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

from pokelance.endpoints import Endpoint
from pokelance.ext.sync._base import SyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache.sync.manager import Evolution as EvolutionCache
    from pokelance.client.sync_client import PokeLanceSyncClient

    _Base = SyncBaseExtension[EvolutionCache]
else:
    _Base = SyncBaseExtension

__all__: tuple[str, ...] = ("Evolution", "setup")


class Evolution(_Base):
    """Extension for evolution related endpoints."""

    def setup(self) -> None:
        routes = {
            "evolution_chain": Endpoint.get_evolution_chain_endpoints(),
            "evolution_trigger": Endpoint.get_evolution_trigger_endpoints(),
        }
        for category, route in routes.items():
            data = self._client.request(route)
            self._cache_manager.load_documents("Evolution", category, data["results"])

    def get_evolution_chain(self, id: int) -> models.EvolutionChain | None:
        """Gets a evolution chain from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.EvolutionChain | None
            The cached model or None."""
        route = Endpoint.get_evolution_chain(id)
        self._validate_resource(self._cache_group.evolution_chain, id, route)
        return self._cache_group.evolution_chain.get(route, None)

    def fetch_evolution_chain(self, id: int) -> models.EvolutionChain:
        """Fetches a evolution chain from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.EvolutionChain
            The fetched model."""
        route = Endpoint.get_evolution_chain(id)
        self._validate_resource(self._cache_group.evolution_chain, id, route)
        data = self._client.request(route)
        return self._cache_group.evolution_chain.setdefault(route, self._cache_group.evolution_chain.from_payload(data))

    def get_evolution_trigger(self, name: str | int) -> models.EvolutionTrigger | None:
        """Gets a evolution trigger from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionTrigger | None
            The cached model or None."""
        route = Endpoint.get_evolution_trigger(name)
        self._validate_resource(self._cache_group.evolution_trigger, name, route)
        return self._cache_group.evolution_trigger.get(route, None)

    def fetch_evolution_trigger(self, name: str | int) -> models.EvolutionTrigger:
        """Fetches a evolution trigger from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.EvolutionTrigger
            The fetched model."""
        route = Endpoint.get_evolution_trigger(name)
        self._validate_resource(self._cache_group.evolution_trigger, name, route)
        data = self._client.request(route)
        return self._cache_group.evolution_trigger.setdefault(
            route, self._cache_group.evolution_trigger.from_payload(data)
        )


def setup(lance: PokeLanceSyncClient) -> None:
    """Sets up the evolution extension."""
    lance.add_extension("evolution", Evolution(lance.http))
