# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

from pokelance.ext.sync._base import SyncBaseExtension
from pokelance.http.endpoints import Endpoint

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache.sync.manager import Game as GameCache
    from pokelance.client.sync_client import PokeLanceSyncClient

    _Base = SyncBaseExtension[GameCache]
else:
    _Base = SyncBaseExtension

__all__: tuple[str, ...] = ("Game", "setup")


class Game(_Base):
    """Extension for game related endpoints."""

    def setup(self) -> None:
        routes = {
            "generation": Endpoint.get_generation_endpoints(),
            "pokedex": Endpoint.get_pokedex_endpoints(),
            "version": Endpoint.get_version_endpoints(),
            "version_group": Endpoint.get_version_group_endpoints(),
        }
        for category, route in routes.items():
            data = self._client.request(route)
            self._cache_manager.load_documents("Game", category, data["results"])

    def get_generation(self, name: str | int) -> models.Generation | None:
        """Gets a generation from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Generation | None
            The cached model or None."""
        route = Endpoint.get_generation(name)
        self._validate_resource(self._cache_group.generation, name, route)
        return self._cache_group.generation.get(route, None)

    def fetch_generation(self, name: str | int) -> models.Generation:
        """Fetches a generation from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Generation
            The fetched model."""
        route = Endpoint.get_generation(name)
        self._validate_resource(self._cache_group.generation, name, route)
        data = self._client.request(route)
        return self._cache_group.generation.setdefault(route, self._cache_group.generation.from_payload(data))

    def get_pokedex(self, name: str | int) -> models.Pokedex | None:
        """Gets a pokedex from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Pokedex | None
            The cached model or None."""
        route = Endpoint.get_pokedex(name)
        self._validate_resource(self._cache_group.pokedex, name, route)
        return self._cache_group.pokedex.get(route, None)

    def fetch_pokedex(self, name: str | int) -> models.Pokedex:
        """Fetches a pokedex from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Pokedex
            The fetched model."""
        route = Endpoint.get_pokedex(name)
        self._validate_resource(self._cache_group.pokedex, name, route)
        data = self._client.request(route)
        return self._cache_group.pokedex.setdefault(route, self._cache_group.pokedex.from_payload(data))

    def get_version(self, name: str | int) -> models.Version | None:
        """Gets a version from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Version | None
            The cached model or None."""
        route = Endpoint.get_version(name)
        self._validate_resource(self._cache_group.version, name, route)
        return self._cache_group.version.get(route, None)

    def fetch_version(self, name: str | int) -> models.Version:
        """Fetches a version from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Version
            The fetched model."""
        route = Endpoint.get_version(name)
        self._validate_resource(self._cache_group.version, name, route)
        data = self._client.request(route)
        return self._cache_group.version.setdefault(route, self._cache_group.version.from_payload(data))

    def get_version_group(self, name: str | int) -> models.VersionGroup | None:
        """Gets a version group from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.VersionGroup | None
            The cached model or None."""
        route = Endpoint.get_version_group(name)
        self._validate_resource(self._cache_group.version_group, name, route)
        return self._cache_group.version_group.get(route, None)

    def fetch_version_group(self, name: str | int) -> models.VersionGroup:
        """Fetches a version group from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.VersionGroup
            The fetched model."""
        route = Endpoint.get_version_group(name)
        self._validate_resource(self._cache_group.version_group, name, route)
        data = self._client.request(route)
        return self._cache_group.version_group.setdefault(route, self._cache_group.version_group.from_payload(data))


def setup(lance: PokeLanceSyncClient) -> None:
    """Sets up the game extension."""
    lance.add_extension("game", Game(lance.http))
