# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

from pokelance.ext.sync._base import SyncBaseExtension
from pokelance.http.endpoints import Endpoint

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache.sync.manager import Machine as MachineCache
    from pokelance.client.sync_client import PokeLanceSyncClient

    _Base = SyncBaseExtension[MachineCache]
else:
    _Base = SyncBaseExtension

__all__: tuple[str, ...] = ("Machine", "setup")


class Machine(_Base):
    """Extension for machine related endpoints."""

    def setup(self) -> None:
        routes = {"machine": Endpoint.get_machine_endpoints()}
        for category, route in routes.items():
            data = self._client.request(route)
            self._cache_manager.load_documents("Machine", category, data["results"])

    def get_machine(self, id: int) -> models.Machine | None:
        """Gets a machine from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Machine | None
            The cached model or None."""
        route = Endpoint.get_machine(id)
        self._validate_resource(self._cache_group.machine, id, route)
        return self._cache_group.machine.get(route, None)

    def fetch_machine(self, id: int) -> models.Machine:
        """Fetches a machine from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Machine
            The fetched model."""
        route = Endpoint.get_machine(id)
        self._validate_resource(self._cache_group.machine, id, route)
        data = self._client.request(route)
        return self._cache_group.machine.setdefault(route, self._cache_group.machine.from_payload(data))


def setup(lance: PokeLanceSyncClient) -> None:
    """Sets up the machine extension."""
    lance.add_extension("machine", Machine(lance.http))
