# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

from typing_extensions import override

from pokelance.endpoints import Endpoint
from pokelance.ext.sync._base import SyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.cache.sync.manager import Move as MoveCache
    from pokelance.client.sync_client import PokeLanceSyncClient

    _Base = SyncBaseExtension[MoveCache]
else:
    _Base = SyncBaseExtension

__all__: tuple[str, ...] = ("Move", "setup")


class Move(_Base):
    """Extension for move related endpoints."""

    @override
    def setup(self) -> None:
        routes = {
            "move": Endpoint.get_move_endpoints(),
            "move_ailment": Endpoint.get_move_ailment_endpoints(),
            "move_battle_style": Endpoint.get_move_battle_style_endpoints(),
            "move_category": Endpoint.get_move_category_endpoints(),
            "move_damage_class": Endpoint.get_move_damage_class_endpoints(),
            "move_learn_method": Endpoint.get_move_learn_method_endpoints(),
            "move_target": Endpoint.get_move_target_endpoints(),
        }
        for category, route in routes.items():
            data = self._client.request(route)
            self._cache_manager.load_documents("Move", category, data["results"])

    def get_move(self, name: str | int) -> models.Move | None:
        """Gets a move from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Move | None
            The cached model or None."""
        route = Endpoint.get_move(name)
        self._validate_resource(self._cache_group.move, name, route)
        return self._cache_group.move.get(route, None)

    def fetch_move(self, name: str | int) -> models.Move:
        """Fetches a move from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.Move
            The fetched model."""
        route = Endpoint.get_move(name)
        self._validate_resource(self._cache_group.move, name, route)
        data = self._client.request(route)
        return self._cache_group.move.setdefault(route, self._cache_group.move.from_payload(data))

    def get_move_ailment(self, name: str | int) -> models.MoveAilment | None:
        """Gets a move ailment from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveAilment | None
            The cached model or None."""
        route = Endpoint.get_move_ailment(name)
        self._validate_resource(self._cache_group.move_ailment, name, route)
        return self._cache_group.move_ailment.get(route, None)

    def fetch_move_ailment(self, name: str | int) -> models.MoveAilment:
        """Fetches a move ailment from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveAilment
            The fetched model."""
        route = Endpoint.get_move_ailment(name)
        self._validate_resource(self._cache_group.move_ailment, name, route)
        data = self._client.request(route)
        return self._cache_group.move_ailment.setdefault(route, self._cache_group.move_ailment.from_payload(data))

    def get_move_battle_style(self, name: str | int) -> models.MoveBattleStyle | None:
        """Gets a move battle style from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveBattleStyle | None
            The cached model or None."""
        route = Endpoint.get_move_battle_style(name)
        self._validate_resource(self._cache_group.move_battle_style, name, route)
        return self._cache_group.move_battle_style.get(route, None)

    def fetch_move_battle_style(self, name: str | int) -> models.MoveBattleStyle:
        """Fetches a move battle style from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveBattleStyle
            The fetched model."""
        route = Endpoint.get_move_battle_style(name)
        self._validate_resource(self._cache_group.move_battle_style, name, route)
        data = self._client.request(route)
        return self._cache_group.move_battle_style.setdefault(
            route, self._cache_group.move_battle_style.from_payload(data)
        )

    def get_move_category(self, name: str | int) -> models.MoveCategory | None:
        """Gets a move category from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveCategory | None
            The cached model or None."""
        route = Endpoint.get_move_category(name)
        self._validate_resource(self._cache_group.move_category, name, route)
        return self._cache_group.move_category.get(route, None)

    def fetch_move_category(self, name: str | int) -> models.MoveCategory:
        """Fetches a move category from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveCategory
            The fetched model."""
        route = Endpoint.get_move_category(name)
        self._validate_resource(self._cache_group.move_category, name, route)
        data = self._client.request(route)
        return self._cache_group.move_category.setdefault(route, self._cache_group.move_category.from_payload(data))

    def get_move_damage_class(self, name: str | int) -> models.MoveDamageClass | None:
        """Gets a move damage class from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveDamageClass | None
            The cached model or None."""
        route = Endpoint.get_move_damage_class(name)
        self._validate_resource(self._cache_group.move_damage_class, name, route)
        return self._cache_group.move_damage_class.get(route, None)

    def fetch_move_damage_class(self, name: str | int) -> models.MoveDamageClass:
        """Fetches a move damage class from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveDamageClass
            The fetched model."""
        route = Endpoint.get_move_damage_class(name)
        self._validate_resource(self._cache_group.move_damage_class, name, route)
        data = self._client.request(route)
        return self._cache_group.move_damage_class.setdefault(
            route, self._cache_group.move_damage_class.from_payload(data)
        )

    def get_move_learn_method(self, name: str | int) -> models.MoveLearnMethod | None:
        """Gets a move learn method from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveLearnMethod | None
            The cached model or None."""
        route = Endpoint.get_move_learn_method(name)
        self._validate_resource(self._cache_group.move_learn_method, name, route)
        return self._cache_group.move_learn_method.get(route, None)

    def fetch_move_learn_method(self, name: str | int) -> models.MoveLearnMethod:
        """Fetches a move learn method from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveLearnMethod
            The fetched model."""
        route = Endpoint.get_move_learn_method(name)
        self._validate_resource(self._cache_group.move_learn_method, name, route)
        data = self._client.request(route)
        return self._cache_group.move_learn_method.setdefault(
            route, self._cache_group.move_learn_method.from_payload(data)
        )

    def get_move_target(self, name: str | int) -> models.MoveTarget | None:
        """Gets a move target from the cache.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveTarget | None
            The cached model or None."""
        route = Endpoint.get_move_target(name)
        self._validate_resource(self._cache_group.move_target, name, route)
        return self._cache_group.move_target.get(route, None)

    def fetch_move_target(self, name: str | int) -> models.MoveTarget:
        """Fetches a move target from the API.

        Parameters
        ----------
        name : str | int
            The name or id.

        Returns
        -------
        models.MoveTarget
            The fetched model."""
        route = Endpoint.get_move_target(name)
        self._validate_resource(self._cache_group.move_target, name, route)
        data = self._client.request(route)
        return self._cache_group.move_target.setdefault(route, self._cache_group.move_target.from_payload(data))


def setup(lance: PokeLanceSyncClient) -> None:
    """Sets up the move extension."""
    lance.add_extension("move", Move(lance.http))
