# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

from typing_extensions import override

from pokelance.cache.sync.manager import Utility as UtilityCache
from pokelance.endpoints import Endpoint
from pokelance.ext.sync._base import SyncBaseExtension

if t.TYPE_CHECKING:
    from pokelance import models
    from pokelance.client.sync_client import PokeLanceSyncClient

__all__: tuple[str, ...] = ("Utility", "setup")


class Utility(SyncBaseExtension[UtilityCache]):
    """Extension for utility related endpoints."""

    @override
    def setup(self) -> None:
        routes = {"language": Endpoint.get_language_endpoints()}
        for category, route in routes.items():
            data = self._client.request(route)
            self._cache_manager.load_documents("Utility", category, data["results"])
        self._cache_group.api_metadata.set_ready()

    def get_language(self, id: int) -> models.Language | None:
        """Gets a language from the cache.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Language | None
            The cached model or None.

        Examples
        --------
        ```python
        language = client.utility.get_language("en")
        if language:
            print(language)
        ```"""
        route = Endpoint.get_language(id)
        self._validate_resource(self._cache_group.language, id, route)
        return self._cache_group.language.get(route, None)

    def fetch_language(self, id: int) -> models.Language:
        """Fetches a language from the API.

        Parameters
        ----------
        id : int
            The resource id.

        Returns
        -------
        models.Language
            The fetched model.

        Examples
        --------
        ```python
        language = client.utility.fetch_language("en")
        print(language)
        ```"""
        route = Endpoint.get_language(id)
        self._validate_resource(self._cache_group.language, id, route)
        data = self._client.request(route)
        return self._cache_group.language.setdefault(route, self._cache_group.language.from_payload(data))

    def get_api_metadata(self) -> models.APIMetadata | None:
        """Gets a api metadata from the cache.

        Returns
        -------
        models.APIMetadata | None
            The cached model or None.

        Examples
        --------
        ```python
        metadata = client.utility.get_api_metadata()
        if metadata:
            print(metadata)
        ```"""
        route = Endpoint.get_api_metadata()
        return self._cache_group.api_metadata.get(route, None)

    def fetch_api_metadata(self) -> models.APIMetadata:
        """Fetches a api metadata from the API.

        Returns
        -------
        models.APIMetadata
            The fetched model.

        Examples
        --------
        ```python
        metadata = client.utility.fetch_api_metadata()
        print(metadata)
        ```"""
        route = Endpoint.get_api_metadata()
        data = self._client.request(route)
        return self._cache_group.api_metadata.setdefault(route, self._cache_group.api_metadata.from_payload(data))


def setup(lance: PokeLanceSyncClient) -> None:
    """Sets up the utility extension."""
    lance.add_extension("utility", Utility(lance.http))
