# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations

import typing as t

import attrs

from pokelance import models
from pokelance.cache.sync.base import SyncCache, SyncCacheGroup

if t.TYPE_CHECKING:
    import collections.abc as cabc

    from pokelance.client.sync_client import PokeLanceSyncClient
    from pokelance.http.endpoints import Route

__all__: tuple[str, ...] = ("SyncCacheGroup", "SyncCacheManager")


@attrs.define(slots=True, kw_only=True)
class Berry(SyncCacheGroup):
    """Cache aggregate for berry endpoints."""

    max_size: int = 100
    berry: SyncCache[Route, models.Berry] = attrs.field(factory=lambda: SyncCache(model=models.Berry, name="berry"))
    berry_firmness: SyncCache[Route, models.BerryFirmness] = attrs.field(
        factory=lambda: SyncCache(model=models.BerryFirmness, name="berry_firmness")
    )
    berry_flavor: SyncCache[Route, models.BerryFlavor] = attrs.field(
        factory=lambda: SyncCache(model=models.BerryFlavor, name="berry_flavor")
    )


@attrs.define(slots=True, kw_only=True)
class Contest(SyncCacheGroup):
    """Cache aggregate for contest endpoints."""

    max_size: int = 100
    contest_type: SyncCache[Route, models.ContestType] = attrs.field(
        factory=lambda: SyncCache(model=models.ContestType, name="contest_type")
    )
    contest_effect: SyncCache[Route, models.ContestEffect] = attrs.field(
        factory=lambda: SyncCache(model=models.ContestEffect, name="contest_effect", endpoint_key_is_id=True)
    )
    super_contest_effect: SyncCache[Route, models.SuperContestEffect] = attrs.field(
        factory=lambda: SyncCache(model=models.SuperContestEffect, name="super_contest_effect", endpoint_key_is_id=True)
    )


@attrs.define(slots=True, kw_only=True)
class Encounter(SyncCacheGroup):
    """Cache aggregate for encounter endpoints."""

    max_size: int = 100
    encounter_method: SyncCache[Route, models.EncounterMethod] = attrs.field(
        factory=lambda: SyncCache(model=models.EncounterMethod, name="encounter_method")
    )
    encounter_condition: SyncCache[Route, models.EncounterCondition] = attrs.field(
        factory=lambda: SyncCache(model=models.EncounterCondition, name="encounter_condition")
    )
    encounter_condition_value: SyncCache[Route, models.EncounterConditionValue] = attrs.field(
        factory=lambda: SyncCache(model=models.EncounterConditionValue, name="encounter_condition_value")
    )


@attrs.define(slots=True, kw_only=True)
class Evolution(SyncCacheGroup):
    """Cache aggregate for evolution endpoints."""

    max_size: int = 100
    evolution_chain: SyncCache[Route, models.EvolutionChain] = attrs.field(
        factory=lambda: SyncCache(model=models.EvolutionChain, name="evolution_chain", endpoint_key_is_id=True)
    )
    evolution_trigger: SyncCache[Route, models.EvolutionTrigger] = attrs.field(
        factory=lambda: SyncCache(model=models.EvolutionTrigger, name="evolution_trigger")
    )


@attrs.define(slots=True, kw_only=True)
class Game(SyncCacheGroup):
    """Cache aggregate for game endpoints."""

    max_size: int = 100
    generation: SyncCache[Route, models.Generation] = attrs.field(
        factory=lambda: SyncCache(model=models.Generation, name="generation")
    )
    pokedex: SyncCache[Route, models.Pokedex] = attrs.field(
        factory=lambda: SyncCache(model=models.Pokedex, name="pokedex")
    )
    version: SyncCache[Route, models.Version] = attrs.field(
        factory=lambda: SyncCache(model=models.Version, name="version")
    )
    version_group: SyncCache[Route, models.VersionGroup] = attrs.field(
        factory=lambda: SyncCache(model=models.VersionGroup, name="version_group")
    )


@attrs.define(slots=True, kw_only=True)
class Item(SyncCacheGroup):
    """Cache aggregate for item endpoints."""

    max_size: int = 100
    item: SyncCache[Route, models.Item] = attrs.field(factory=lambda: SyncCache(model=models.Item, name="item"))
    item_attribute: SyncCache[Route, models.ItemAttribute] = attrs.field(
        factory=lambda: SyncCache(model=models.ItemAttribute, name="item_attribute")
    )
    item_category: SyncCache[Route, models.ItemCategory] = attrs.field(
        factory=lambda: SyncCache(model=models.ItemCategory, name="item_category")
    )
    item_fling_effect: SyncCache[Route, models.ItemFlingEffect] = attrs.field(
        factory=lambda: SyncCache(model=models.ItemFlingEffect, name="item_fling_effect")
    )
    item_pocket: SyncCache[Route, models.ItemPocket] = attrs.field(
        factory=lambda: SyncCache(model=models.ItemPocket, name="item_pocket")
    )
    currency: SyncCache[Route, models.Currency] = attrs.field(
        factory=lambda: SyncCache(model=models.Currency, name="currency")
    )


@attrs.define(slots=True, kw_only=True)
class Location(SyncCacheGroup):
    """Cache aggregate for location endpoints."""

    max_size: int = 100
    location: SyncCache[Route, models.Location] = attrs.field(
        factory=lambda: SyncCache(model=models.Location, name="location")
    )
    location_area: SyncCache[Route, models.LocationArea] = attrs.field(
        factory=lambda: SyncCache(model=models.LocationArea, name="location_area")
    )
    pal_park_area: SyncCache[Route, models.PalParkArea] = attrs.field(
        factory=lambda: SyncCache(model=models.PalParkArea, name="pal_park_area")
    )
    region: SyncCache[Route, models.Region] = attrs.field(factory=lambda: SyncCache(model=models.Region, name="region"))


@attrs.define(slots=True, kw_only=True)
class Machine(SyncCacheGroup):
    """Cache aggregate for machine endpoints."""

    max_size: int = 100
    machine: SyncCache[Route, models.Machine] = attrs.field(
        factory=lambda: SyncCache(model=models.Machine, name="machine", endpoint_key_is_id=True)
    )


@attrs.define(slots=True, kw_only=True)
class Move(SyncCacheGroup):
    """Cache aggregate for move endpoints."""

    max_size: int = 100
    move: SyncCache[Route, models.Move] = attrs.field(factory=lambda: SyncCache(model=models.Move, name="move"))
    move_ailment: SyncCache[Route, models.MoveAilment] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveAilment, name="move_ailment")
    )
    move_battle_style: SyncCache[Route, models.MoveBattleStyle] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveBattleStyle, name="move_battle_style")
    )
    move_category: SyncCache[Route, models.MoveCategory] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveCategory, name="move_category")
    )
    move_damage_class: SyncCache[Route, models.MoveDamageClass] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveDamageClass, name="move_damage_class")
    )
    move_learn_method: SyncCache[Route, models.MoveLearnMethod] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveLearnMethod, name="move_learn_method")
    )
    move_target: SyncCache[Route, models.MoveTarget] = attrs.field(
        factory=lambda: SyncCache(model=models.MoveTarget, name="move_target")
    )


@attrs.define(slots=True, kw_only=True)
class Pokemon(SyncCacheGroup):
    """Cache aggregate for pokemon endpoints."""

    max_size: int = 100
    ability: SyncCache[Route, models.Ability] = attrs.field(
        factory=lambda: SyncCache(model=models.Ability, name="ability")
    )
    characteristic: SyncCache[Route, models.Characteristic] = attrs.field(
        factory=lambda: SyncCache(model=models.Characteristic, name="characteristic", endpoint_key_is_id=True)
    )
    egg_group: SyncCache[Route, models.EggGroup] = attrs.field(
        factory=lambda: SyncCache(model=models.EggGroup, name="egg_group")
    )
    gender: SyncCache[Route, models.Gender] = attrs.field(factory=lambda: SyncCache(model=models.Gender, name="gender"))
    growth_rate: SyncCache[Route, models.GrowthRate] = attrs.field(
        factory=lambda: SyncCache(model=models.GrowthRate, name="growth_rate")
    )
    nature: SyncCache[Route, models.Nature] = attrs.field(factory=lambda: SyncCache(model=models.Nature, name="nature"))
    pokeathlon_stat: SyncCache[Route, models.PokeathlonStat] = attrs.field(
        factory=lambda: SyncCache(model=models.PokeathlonStat, name="pokeathlon_stat")
    )
    pokemon: SyncCache[Route, models.Pokemon] = attrs.field(
        factory=lambda: SyncCache(model=models.Pokemon, name="pokemon")
    )
    pokemon_color: SyncCache[Route, models.PokemonColor] = attrs.field(
        factory=lambda: SyncCache(model=models.PokemonColor, name="pokemon_color")
    )
    pokemon_form: SyncCache[Route, models.PokemonForm] = attrs.field(
        factory=lambda: SyncCache(model=models.PokemonForm, name="pokemon_form")
    )
    pokemon_habitat: SyncCache[Route, models.PokemonHabitats] = attrs.field(
        factory=lambda: SyncCache(model=models.PokemonHabitats, name="pokemon_habitat")
    )
    pokemon_shape: SyncCache[Route, models.PokemonShape] = attrs.field(
        factory=lambda: SyncCache(model=models.PokemonShape, name="pokemon_shape")
    )
    pokemon_species: SyncCache[Route, models.PokemonSpecies] = attrs.field(
        factory=lambda: SyncCache(model=models.PokemonSpecies, name="pokemon_species")
    )
    stat: SyncCache[Route, models.Stat] = attrs.field(factory=lambda: SyncCache(model=models.Stat, name="stat"))
    type: SyncCache[Route, models.Type] = attrs.field(factory=lambda: SyncCache(model=models.Type, name="type"))
    location_area_encounter: SyncCache[Route, list[models.LocationAreaEncounter]] = attrs.field(
        factory=lambda: SyncCache(
            model=models.LocationAreaEncounter, name="location_area_encounter", url_suffix="/encounters", is_list=True
        )
    )


@attrs.define(slots=True, kw_only=True)
class Utility(SyncCacheGroup):
    """Cache aggregate for utility endpoints."""

    max_size: int = 100
    language: SyncCache[Route, models.Language] = attrs.field(
        factory=lambda: SyncCache(model=models.Language, name="language", endpoint_key_is_id=True)
    )
    api_metadata: SyncCache[Route, models.APIMetadata] = attrs.field(
        factory=lambda: SyncCache(model=models.APIMetadata, name="api_metadata", endpoint_key_is_id=True)
    )


@attrs.define(slots=True, kw_only=True)
class SyncCacheManager:
    """Top-level sync cache manager."""

    client: PokeLanceSyncClient
    max_size: int = 100
    berry: Berry = attrs.field(factory=Berry)
    contest: Contest = attrs.field(factory=Contest)
    encounter: Encounter = attrs.field(factory=Encounter)
    evolution: Evolution = attrs.field(factory=Evolution)
    game: Game = attrs.field(factory=Game)
    item: Item = attrs.field(factory=Item)
    location: Location = attrs.field(factory=Location)
    machine: Machine = attrs.field(factory=Machine)
    move: Move = attrs.field(factory=Move)
    pokemon: Pokemon = attrs.field(factory=Pokemon)
    utility: Utility = attrs.field(factory=Utility)

    def _walk_aggregates(self) -> cabc.Iterator[SyncCacheGroup]:
        """Yield all child cache aggregates."""
        for field in attrs.fields(self.__class__):
            val = getattr(self, field.name)
            if isinstance(val, SyncCacheGroup):
                yield val

    def __attrs_post_init__(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.set_size(self.max_size)
            aggregate.set_client(self.client)

    def set_size(self, max_size: int = 100) -> None:
        self.max_size = max_size
        for aggregate in self._walk_aggregates():
            aggregate.set_size(max_size)

    def load_documents(self, category: str, _type: str, data: list[dict[str, str]]) -> None:
        getattr(getattr(self, category.lower()), _type).load_documents(data)

    def clear(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.clear()

    def reset(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.reset()

    def wait_until_ready(self) -> None:
        """Wait for all sub-caches in all aggregates to be ready."""
        for aggregate in self._walk_aggregates():
            aggregate.wait_until_ready()
