# AUTO-GENERATED by scripts/gen_scripts/generate_all.py
# DO NOT EDIT MANUALLY
# Edit scripts/gen_scripts/_registry.py instead.

from __future__ import annotations
import typing as t
import attrs
from pokelance import models
from pokelance.cache.sync.base import SyncBaseCache, SyncCacheGroup
from pokelance.http.endpoints import Route
if t.TYPE_CHECKING:
    from pokelance.client.sync_client import PokeLanceSyncClient
__all__ = ('SyncCacheManager', 'SyncCacheGroup')



@attrs.define(slots=True, kw_only=True)
class Berry(SyncCacheGroup):
    """Cache aggregate for berry endpoints."""
    max_size: int = 100
    berry: SyncBaseCache[Route, models.Berry] = attrs.field(factory=lambda: SyncBaseCache(model=models.Berry, name='berry'))
    berry_firmness: SyncBaseCache[Route, models.BerryFirmness] = attrs.field(factory=lambda: SyncBaseCache(model=models.BerryFirmness, name='berry_firmness'))
    berry_flavor: SyncBaseCache[Route, models.BerryFlavor] = attrs.field(factory=lambda: SyncBaseCache(model=models.BerryFlavor, name='berry_flavor'))



@attrs.define(slots=True, kw_only=True)
class Contest(SyncCacheGroup):
    """Cache aggregate for contest endpoints."""
    max_size: int = 100
    contest_type: SyncBaseCache[Route, models.ContestType] = attrs.field(factory=lambda: SyncBaseCache(model=models.ContestType, name='contest_type'))
    contest_effect: SyncBaseCache[Route, models.ContestEffect] = attrs.field(factory=lambda: SyncBaseCache(model=models.ContestEffect, name='contest_effect', endpoint_key_is_id=True))
    super_contest_effect: SyncBaseCache[Route, models.SuperContestEffect] = attrs.field(factory=lambda: SyncBaseCache(model=models.SuperContestEffect, name='super_contest_effect', endpoint_key_is_id=True))



@attrs.define(slots=True, kw_only=True)
class Encounter(SyncCacheGroup):
    """Cache aggregate for encounter endpoints."""
    max_size: int = 100
    encounter_method: SyncBaseCache[Route, models.EncounterMethod] = attrs.field(factory=lambda: SyncBaseCache(model=models.EncounterMethod, name='encounter_method'))
    encounter_condition: SyncBaseCache[Route, models.EncounterCondition] = attrs.field(factory=lambda: SyncBaseCache(model=models.EncounterCondition, name='encounter_condition'))
    encounter_condition_value: SyncBaseCache[Route, models.EncounterConditionValue] = attrs.field(factory=lambda: SyncBaseCache(model=models.EncounterConditionValue, name='encounter_condition_value'))



@attrs.define(slots=True, kw_only=True)
class Evolution(SyncCacheGroup):
    """Cache aggregate for evolution endpoints."""
    max_size: int = 100
    evolution_chain: SyncBaseCache[Route, models.EvolutionChain] = attrs.field(factory=lambda: SyncBaseCache(model=models.EvolutionChain, name='evolution_chain', endpoint_key_is_id=True))
    evolution_trigger: SyncBaseCache[Route, models.EvolutionTrigger] = attrs.field(factory=lambda: SyncBaseCache(model=models.EvolutionTrigger, name='evolution_trigger'))



@attrs.define(slots=True, kw_only=True)
class Game(SyncCacheGroup):
    """Cache aggregate for game endpoints."""
    max_size: int = 100
    generation: SyncBaseCache[Route, models.Generation] = attrs.field(factory=lambda: SyncBaseCache(model=models.Generation, name='generation'))
    pokedex: SyncBaseCache[Route, models.Pokedex] = attrs.field(factory=lambda: SyncBaseCache(model=models.Pokedex, name='pokedex'))
    version: SyncBaseCache[Route, models.Version] = attrs.field(factory=lambda: SyncBaseCache(model=models.Version, name='version'))
    version_group: SyncBaseCache[Route, models.VersionGroup] = attrs.field(factory=lambda: SyncBaseCache(model=models.VersionGroup, name='version_group'))



@attrs.define(slots=True, kw_only=True)
class Item(SyncCacheGroup):
    """Cache aggregate for item endpoints."""
    max_size: int = 100
    item: SyncBaseCache[Route, models.Item] = attrs.field(factory=lambda: SyncBaseCache(model=models.Item, name='item'))
    item_attribute: SyncBaseCache[Route, models.ItemAttribute] = attrs.field(factory=lambda: SyncBaseCache(model=models.ItemAttribute, name='item_attribute'))
    item_category: SyncBaseCache[Route, models.ItemCategory] = attrs.field(factory=lambda: SyncBaseCache(model=models.ItemCategory, name='item_category'))
    item_fling_effect: SyncBaseCache[Route, models.ItemFlingEffect] = attrs.field(factory=lambda: SyncBaseCache(model=models.ItemFlingEffect, name='item_fling_effect'))
    item_pocket: SyncBaseCache[Route, models.ItemPocket] = attrs.field(factory=lambda: SyncBaseCache(model=models.ItemPocket, name='item_pocket'))



@attrs.define(slots=True, kw_only=True)
class Location(SyncCacheGroup):
    """Cache aggregate for location endpoints."""
    max_size: int = 100
    location: SyncBaseCache[Route, models.Location] = attrs.field(factory=lambda: SyncBaseCache(model=models.Location, name='location'))
    location_area: SyncBaseCache[Route, models.LocationArea] = attrs.field(factory=lambda: SyncBaseCache(model=models.LocationArea, name='location_area'))
    pal_park_area: SyncBaseCache[Route, models.PalParkArea] = attrs.field(factory=lambda: SyncBaseCache(model=models.PalParkArea, name='pal_park_area'))
    region: SyncBaseCache[Route, models.Region] = attrs.field(factory=lambda: SyncBaseCache(model=models.Region, name='region'))



@attrs.define(slots=True, kw_only=True)
class Machine(SyncCacheGroup):
    """Cache aggregate for machine endpoints."""
    max_size: int = 100
    machine: SyncBaseCache[Route, models.Machine] = attrs.field(factory=lambda: SyncBaseCache(model=models.Machine, name='machine', endpoint_key_is_id=True))



@attrs.define(slots=True, kw_only=True)
class Move(SyncCacheGroup):
    """Cache aggregate for move endpoints."""
    max_size: int = 100
    move: SyncBaseCache[Route, models.Move] = attrs.field(factory=lambda: SyncBaseCache(model=models.Move, name='move'))
    move_ailment: SyncBaseCache[Route, models.MoveAilment] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveAilment, name='move_ailment'))
    move_battle_style: SyncBaseCache[Route, models.MoveBattleStyle] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveBattleStyle, name='move_battle_style'))
    move_category: SyncBaseCache[Route, models.MoveCategory] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveCategory, name='move_category'))
    move_damage_class: SyncBaseCache[Route, models.MoveDamageClass] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveDamageClass, name='move_damage_class'))
    move_learn_method: SyncBaseCache[Route, models.MoveLearnMethod] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveLearnMethod, name='move_learn_method'))
    move_target: SyncBaseCache[Route, models.MoveTarget] = attrs.field(factory=lambda: SyncBaseCache(model=models.MoveTarget, name='move_target'))



@attrs.define(slots=True, kw_only=True)
class Pokemon(SyncCacheGroup):
    """Cache aggregate for pokemon endpoints."""
    max_size: int = 100
    ability: SyncBaseCache[Route, models.Ability] = attrs.field(factory=lambda: SyncBaseCache(model=models.Ability, name='ability'))
    characteristic: SyncBaseCache[Route, models.Characteristic] = attrs.field(factory=lambda: SyncBaseCache(model=models.Characteristic, name='characteristic', endpoint_key_is_id=True))
    egg_group: SyncBaseCache[Route, models.EggGroup] = attrs.field(factory=lambda: SyncBaseCache(model=models.EggGroup, name='egg_group'))
    gender: SyncBaseCache[Route, models.Gender] = attrs.field(factory=lambda: SyncBaseCache(model=models.Gender, name='gender'))
    growth_rate: SyncBaseCache[Route, models.GrowthRate] = attrs.field(factory=lambda: SyncBaseCache(model=models.GrowthRate, name='growth_rate'))
    nature: SyncBaseCache[Route, models.Nature] = attrs.field(factory=lambda: SyncBaseCache(model=models.Nature, name='nature'))
    pokeathlon_stat: SyncBaseCache[Route, models.PokeathlonStat] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokeathlonStat, name='pokeathlon_stat'))
    pokemon: SyncBaseCache[Route, models.Pokemon] = attrs.field(factory=lambda: SyncBaseCache(model=models.Pokemon, name='pokemon'))
    pokemon_color: SyncBaseCache[Route, models.PokemonColor] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokemonColor, name='pokemon_color'))
    pokemon_form: SyncBaseCache[Route, models.PokemonForm] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokemonForm, name='pokemon_form'))
    pokemon_habitat: SyncBaseCache[Route, models.PokemonHabitats] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokemonHabitats, name='pokemon_habitat'))
    pokemon_shape: SyncBaseCache[Route, models.PokemonShape] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokemonShape, name='pokemon_shape'))
    pokemon_species: SyncBaseCache[Route, models.PokemonSpecies] = attrs.field(factory=lambda: SyncBaseCache(model=models.PokemonSpecies, name='pokemon_species'))
    stat: SyncBaseCache[Route, models.Stat] = attrs.field(factory=lambda: SyncBaseCache(model=models.Stat, name='stat'))
    type: SyncBaseCache[Route, models.Type] = attrs.field(factory=lambda: SyncBaseCache(model=models.Type, name='type'))
    location_area_encounter: SyncBaseCache[Route, t.Sequence[models.LocationAreaEncounter]] = attrs.field(factory=lambda: SyncBaseCache(model=models.LocationAreaEncounter, name='location_area_encounter', url_suffix='/encounters', is_list=True))



@attrs.define(slots=True, kw_only=True)
class Utility(SyncCacheGroup):
    """Cache aggregate for utility endpoints."""
    max_size: int = 100
    language: SyncBaseCache[Route, models.Language] = attrs.field(factory=lambda: SyncBaseCache(model=models.Language, name='language', endpoint_key_is_id=True))
    api_metadata: SyncBaseCache[Route, models.APIMetadata] = attrs.field(factory=lambda: SyncBaseCache(model=models.APIMetadata, name='api_metadata', endpoint_key_is_id=True))



@attrs.define(slots=True, kw_only=True)
class SyncCacheManager:
    """Top-level sync cache manager."""
    client: 'PokeLanceSyncClient'
    max_size: int = 100
    berry: Berry = attrs.field(factory=Berry)
    contest: Contest = attrs.field(factory=Contest)
    encounter: Encounter = attrs.field(factory=Encounter)
    evolution: Evolution = attrs.field(factory=Evolution)
    game: Game = attrs.field(factory=Game)
    item: Item = attrs.field(factory=Item)
    location: Location = attrs.field(factory=Location)
    machine: Machine = attrs.field(factory=Machine)
    move: Move = attrs.field(factory=Move)
    pokemon: Pokemon = attrs.field(factory=Pokemon)
    utility: Utility = attrs.field(factory=Utility)

    def _walk_aggregates(self) -> t.Iterator[SyncCacheGroup]:
        """Yield all child cache aggregates."""
        for field in attrs.fields(self.__class__):
            val = getattr(self, field.name)
            if isinstance(val, SyncCacheGroup):
                yield val

    def __attrs_post_init__(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.set_size(self.max_size)
            aggregate.set_client(self.client)

    def set_size(self, max_size: int=100) -> None:
        self.max_size = max_size
        for aggregate in self._walk_aggregates():
            aggregate.set_size(max_size)

    def load_documents(self, category: str, _type: str, data: t.List[t.Dict[str, str]]) -> None:
        getattr(getattr(self, category.lower()), _type).load_documents(data)

    def clear(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.clear()

    def reset(self) -> None:
        for aggregate in self._walk_aggregates():
            aggregate.reset()

    def wait_until_ready(self) -> None:
        """Wait for all sub-caches in all aggregates to be ready."""
        for aggregate in self._walk_aggregates():
            aggregate.wait_until_ready()
