name: Release on GitHub

on:
  push:
    tags:
      - v*

jobs:
  release-asset:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.changelog.outputs.version }} - (${{ steps.changelog.outputs.date }})
          tag: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          prerelease: $${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: $${{ steps.changelog.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
