name: Release on GitHub

on:
  push:
    branches: ["master", "main", "rewrite", "develop"]

jobs:
  release-asset:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version from tag
        id: tag_name
        run:
          |
          echo ::set-output name=tag_name::$(git describe --tags --abbrev=0 | sed 's/v//')

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.tag_name.outputs.tag_name }}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.changelog.outputs.date }} (${{ steps.changelog.outputs.version }})
          tag: ${{ steps.tag_name.outputs.tag_name }}
          body: ${{ steps.changelog.outputs.description }}
          prerelease: $${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: $${{ steps.changelog.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
